# Generated by Django 3.0.7 on 2020-07-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Booking',
        ),
    ]
