# Generated by Django 3.0.7 on 2020-07-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_costumerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerinfo',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='costumerinfo',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
