# Generated by Django 3.0.7 on 2020-07-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20200711_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerinfo',
            name='booking_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
