# Generated by Django 3.0.7 on 2020-07-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20200711_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingPlace',
        ),
    ]
