# Generated by Django 3.0.7 on 2020-07-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20200711_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='user',
        ),
    ]
