# Generated by Django 3.0.7 on 2020-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_auto_20200711_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerinfo',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
