# Generated by Django 3.0.7 on 2020-07-15 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0025_auto_20200715_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='CostumerInfo',
            new_name='CustomerInfo',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='costumer',
            new_name='customer',
        ),
    ]
