# Generated by Django 3.0.7 on 2020-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_auto_20200715_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
