# Generated by Django 3.0.7 on 2020-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
