# Generated by Django 3.0.7 on 2020-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('Usa', 'Usa')], max_length=100, null=True),
        ),
    ]
