# Generated by Django 3.0.7 on 2020-07-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_place_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='color',
            field=models.CharField(choices=[('Asia', 'danger'), ('Europe', 'primary'), ('Usa', 'success')], max_length=100, null=True),
        ),
    ]
